subplot(1,5,1);
imshow('urban_after_train.jpg');
xlabel('Urban');
subplot(1,5,2);
imshow('arable_after_train.jpg');
xlabel('Arable land');
subplot(1,5,3);
imshow('vegetation_after_train.jpg');
xlabel('Vegetation');
subplot(1,5,4);
imshow('water_after_train2.jpg');
xlabel('Water');
subplot(1,5,5);
imshow('wetlands_after_train.jpg');
xlabel('Wetlands');